In [3]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [4]:
df=pd.read_csv("hotel_cancellation_data.csv")

In [5]:
df

,Booking_ID,Hotel_Name,Booking_Date,Check_In_Date,Check_Out_Date,Customer_Nationality,Booking_Platform,Room_Type_Booked,Number_of_Adults,Number_of_Children,...,Special_Requests,Payment_Method,Is_Repeated_Guest,Deposit_Type,Average_Daily_Rate,Is_Weekend_Stay,Required_Car_Parking_Spaces,Total_Special_Requests,Customer_Rating,Cancellation_Status
0,BK001000,Heritage Hotel,2023-04-25,2023-05-07,2023-05-19,Germany,Direct Booking,Family Room,2,0,...,NaN,Credit Card,0,No Deposit,766.8,1,2,0,NaN,1
1,BK001001,Boutique Hotel Central,2023-07-23,2024-06-19,2024-07-01,Japan,Hotels.com,Family Room,4,2,...,"Early Check-in, Extra Bed",Debit Card,1,No Deposit,889.2,0,1,2,6.0,0
2,BK001002,Grand Plaza Hotel,2024-04-15,2025-01-14,2025-01-16,Mexico,Hotels.com,Deluxe,3,2,...,Early Check-in,Credit Card,0,Partial,562.5,0,1,1,NaN,1
3,BK001003,Heritage Hotel,2024-01-09,2024-04-01,2024-04-07,France,Direct Booking,Executive Suite,1,1,...,"Late Checkout, High Floor",PayPal,0,No Deposit,882.5,0,0,2,NaN,0
4,BK001004,Luxury Palace,2023-10-02,2023-11-04,2023-11-08,Mexico,Phone Booking,Presidential Suite,2,3,...,Early Check-in,Corporate Billing,1,Partial,987.0,1,1,1,5.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,BK002495,City Center Inn,2023-03-14,2023-07-17,2023-07-31,Italy,Direct Booking,Double Room,1,2,...,NaN,Corporate Billing,0,No Deposit,293.7,0,1,0,NaN,0
1496,BK002496,Seaside Resort,2023-09-27,2023-11-28,2023-12-08,UAE,Direct Booking,Studio,4,0,...,NaN,Cash on Arrival,0,Partial,358.8,0,2,0,NaN,0
1497,BK002497,Spa & Wellness Resort,2023-05-09,2023-10-17,2023-10-31,Spain,Phone Booking,Suite,3,3,...,NaN,Debit Card,1,No Deposit,578.0,0,0,0,2.0,0
1498,BK002498,Seaside Resort,2024-07-29,2025-06-18,2025-06-20,Germany,Booking.com,Presidential Suite,1,1,...,NaN,PayPal,1,No Deposit,560.0,0,2,0,3.0,1
1499,BK002499,Airport Hotel,2023-02-18,2023-09-03,2023-09-11,UK,Travel Agency,Single Room,4,1,...,"Connecting Rooms, Airport Pickup",PayPal,1,No Deposit,103.5,1,0,2,10.0,0

In [11]:
df.columns

Index(['Booking_ID', 'Hotel_Name', 'Booking_Date', 'Check_In_Date',
       'Check_Out_Date', 'Customer_Nationality', 'Booking_Platform',
       'Room_Type_Booked', 'Number_of_Adults', 'Number_of_Children',
       'Number_of_Nights', 'Total_Guests', 'Room_Price_Per_Night',
       'Total_Price', 'Meal_Plan', 'Cancellation_Policy', 'Lead_Time',
       'Previous_Cancellations', 'Previous_Bookings_Not_Canceled',
       'Special_Requests', 'Payment_Method', 'Is_Repeated_Guest',
       'Deposit_Type', 'Average_Daily_Rate', 'Is_Weekend_Stay',
       'Required_Car_Parking_Spaces', 'Total_Special_Requests',
       'Customer_Rating', 'Cancellation_Status'],
      dtype='object')

### How big is data?

In [21]:
df.shape

(1500, 29)

### How does the data look like?

In [22]:
df.sample(10)

,Booking_ID,Hotel_Name,Booking_Date,Check_In_Date,Check_Out_Date,Customer_Nationality,Booking_Platform,Room_Type_Booked,Number_of_Adults,Number_of_Children,...,Special_Requests,Payment_Method,Is_Repeated_Guest,Deposit_Type,Average_Daily_Rate,Is_Weekend_Stay,Required_Car_Parking_Spaces,Total_Special_Requests,Customer_Rating,Cancellation_Status
1295,BK002295,Boutique Hotel Central,2024-10-23,2025-10-18,2025-10-22,Italy,Expedia,Twin Room,1,0,...,"Extra Bed, None, Early Check-in",Cash on Arrival,1,Full,320.4,1,1,3,6.0,0
987,BK001987,Spa & Wellness Resort,2023-09-06,2024-09-01,2024-09-15,Germany,Travel Agency,Studio,4,2,...,NaN,Cash on Arrival,0,No Deposit,253.5,1,0,0,NaN,1
1357,BK002357,Heritage Hotel,2024-12-13,2025-03-10,2025-03-12,Spain,Direct Booking,Family Room,4,0,...,"Early Check-in, Baby Cot",Credit Card,0,No Deposit,882.0,0,2,2,NaN,0
932,BK001932,Modern Stays,2024-06-11,2024-08-22,2024-08-30,Australia,Travel Agency,Single Room,1,1,...,NaN,Debit Card,1,Partial,426.6,0,2,0,6.0,0
1197,BK002197,Mountain View Lodge,2024-03-03,2024-04-14,2024-04-21,Spain,Agoda,Standard,1,3,...,"Early Check-in, Airport Pickup, Late Checkout",Corporate Billing,1,No Deposit,245.0,1,1,3,8.0,1
627,BK001627,Luxury Palace,2023-02-10,2023-08-15,2023-08-22,India,Trivago,Double Room,4,0,...,High Floor,Bank Transfer,1,No Deposit,146.3,0,0,1,6.0,1
1477,BK002477,Modern Stays,2023-02-23,2023-07-12,2023-07-15,Canada,Travel Agency,Presidential Suite,4,2,...,NaN,Debit Card,1,No Deposit,406.0,0,0,0,4.0,0
534,BK001534,Spa & Wellness Resort,2024-11-27,2025-04-24,2025-05-08,Australia,Trivago,Single Room,2,1,...,"Baby Cot, High Floor, Airport Pickup",Cash on Arrival,1,No Deposit,428.4,0,1,3,3.0,0
1436,BK002436,Grand Plaza Hotel,2024-08-09,2024-08-14,2024-08-21,Brazil,Kayak,Twin Room,1,1,...,"None, Late Checkout",Bank Transfer,1,Full,572.4,0,0,2,5.0,0
198,BK001198,Spa & Wellness Resort,2024-12-10,2025-04-16,2025-04-21,Spain,Corporate Account,Executive Suite,4,1,...,"Late Checkout, Extra Bed",Debit Card,1,No Deposit,375.0,0,2,2,3.0,0

### What is the type of columns?

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 29 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Booking_ID                      1500 non-null   object
 1   Hotel_Name                      1500 non-null   object
 2   Booking_Date                    1500 non-null   object
 3   Check_In_Date                   1500 non-null   object
 4   Check_Out_Date                  1500 non-null   object
 5   Customer_Nationality            1500 non-null   object
 6   Booking_Platform                1500 non-null   object
 7   Room_Type_Booked                1500 non-null   object
 8   Number_of_Adults                1500 non-null   int64
 9   Number_of_Children              1500 non-null   int64
 10  Number_of_Nights                1500 non-null   int64
 11  Total_Guests                    1500 non-null   int64
 12  Room_Price_Per_Night            1500 non-null   float64
 13  Total_Price                     1500 non-null   float64
 14  Meal_Plan                       1500 non-null   object
 15  Cancellation_Policy             1500 non-null   object
 16  Lead_Time                       1500 non-null   int64
 17  Previous_Cancellations          1500 non-null   int64
 18  Previous_Bookings_Not_Canceled  1500 non-null   int64
 19  Special_Requests                1063 non-null   object
 20  Payment_Method                  1500 non-null   object
 21  Is_Repeated_Guest               1500 non-null   int64
 22  Deposit_Type                    1500 non-null   object
 23  Average_Daily_Rate              1500 non-null   float64
 24  Is_Weekend_Stay                 1500 non-null   int64
 25  Required_Car_Parking_Spaces     1500 non-null   int64
 26  Total_Special_Requests          1500 non-null   int64
 27  Customer_Rating                 734 non-null    float64
 28  Cancellation_Status             1500 non-null   int64
dtypes: float64(4), int64(12), object(13)
memory usage: 340.0+ KB

### Are there any missing values?

In [19]:
df.isnull().sum()

Booking_ID                          0
Hotel_Name                          0
Booking_Date                        0
Check_In_Date                       0
Check_Out_Date                      0
Customer_Nationality                0
Booking_Platform                    0
Room_Type_Booked                    0
Number_of_Adults                    0
Number_of_Children                  0
Number_of_Nights                    0
Total_Guests                        0
Room_Price_Per_Night                0
Total_Price                         0
Meal_Plan                           0
Cancellation_Policy                 0
Lead_Time                           0
Previous_Cancellations              0
Previous_Bookings_Not_Canceled      0
Special_Requests                  437
Payment_Method                      0
Is_Repeated_Guest                   0
Deposit_Type                        0
Average_Daily_Rate                  0
Is_Weekend_Stay                     0
Required_Car_Parking_Spaces         0
Total_Special_Requests              0
Customer_Rating                   766
Cancellation_Status                 0
dtype: int64

In [20]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Number_of_Adults,1500.0,2.529333,1.128711,1.0,2.00,2.0,4.00,4.0
Number_of_Children,1500.0,1.500667,1.129683,0.0,0.00,1.0,3.00,3.0
Number_of_Nights,1500.0,7.576667,4.079119,1.0,4.00,8.0,11.00,14.0
Total_Guests,1500.0,4.030000,1.589167,1.0,3.00,4.0,5.00,7.0
Room_Price_Per_Night,1500.0,501.704600,327.993113,72.9,270.65,426.7,624.70,1743.0
Total_Price,1500.0,3774.386267,3426.428084,91.3,1309.50,2823.0,5047.95,23079.0
Lead_Time,1500.0,177.766667,104.536361,0.0,86.00,178.0,265.25,365.0
Previous_Cancellations,1500.0,2.423333,1.693724,0.0,1.00,2.0,4.00,5.0
Previous_Bookings_Not_Canceled,1500.0,5.053333,3.106057,0.0,2.00,5.0,8.00,10.0
Is_Repeated_Guest,1500.0,0.489333,0.500053,0.0,0.00,0.0,1.00,1.0
Average_Daily_Rate,1500.0,501.704600,327.993113,72.9,270.65,426.7,624.70,1743.0
Is_Weekend_Stay,1500.0,0.418000,0.493395,0.0,0.00,0.0,1.00,1.0
Required_Car_Parking_Spaces,1500.0,0.980000,0.809137,0.0,0.00,1.0,2.00,2.0
Total_Special_Requests,1500.0,1.456667,1.105563,0.0,0.00,1.0,2.00,3.0
Customer_Rating,734.0,6.446866,2.488563,1.0,4.25,7.0,9.00,10.0
Cancellation_Status,1500.0,0.377333,0.484881,0.0,0.00,0.0,1.00,1.0